{
 "BASH": (None, "/bin/bash"),
 "BASHOPTS": ("-r", "checkwinsize:cmdhist:complete_fullquote:expand_aliases:extglob:extquote:force_fignore:globasciiranges:globskipdots:histappend:interactive_comments:login_shell:patsub_replacement:progcomp:promptvars:sourcepath"),
 "BASHPID": ("-i", ""),
 "BASHPID2": ("-i", "2"),
 "BASH_ALIASES": (None, []),
 "BASH_ARGC": (None, ["0"]),
 "BASH_VERSINFO": (None, ["5", "2", "21", "1", "release", "x86_64-pc-linux-gnu"]),
 "COMP_WORDBREAKS": (None, ' \\t\\n"><=;|&(:'),
 "IFS": (None, ' \\t\\n'),
 "IFS2": (None, "\n "),
 "LESSOPEN": ("-x", "| /usr/bin/lesspipe %s"),
 "HOSTNAME": (None, "redoxvm"),
 "HOSTTYPE": ("-r", "x86_64"),
 "HUSHLOGIN": ("-x", "FALSE"),
 "TEST": ("-x", ""),
 "TEST2": ("-x", ""),
}
